### ISSUE TITLE
Version on slippi.gg

### ISSUE THREAD

**Issue by caseyavila** [project-slippi/slippi-desktop-app#108]
Currently the website lists version 1.6.4 as the latest and provides downloads for this version, but version 1.6.5 seems to already be out.

Also would there be a possibility to open-source the website itself, or at least a way to provide feedback about it?

**Comment by NikhilNarayana** [comment]
Yeah the version being wrong would be my bad, I released it rather suddenly and Fizzi hasn't had the time to update the website. We'll get it updated at some point.

The website is not planned to be open sourced in the future, but if you want to leave feedback feel free to do so in the dev-general channel on our discord.
