### ISSUE TITLE
Developer Mode does not work even with gecko code enabled

### ISSUE THREAD

**Issue by cnkeats** [project-slippi/slippi-desktop-app#136]
With Desktop App v1.6.8, Developer mode no longer works in replays, even if the gecko code is enabled. This prevents users from pausing, turning the camera, showing hitboxes, etc. and is a regression from v1.6.7.

This has been brought up in the Discord a few times, but I am opening an issue to help track that it still needs to be fixed.

**Comment by NikhilNarayana** [comment]
Fixed in 1.6.9
