### ISSUE TITLE
stderr maxBuffer length exceeded

### ISSUE THREAD

**Issue by NateDogg1232** [project-slippi/slippi-desktop-app#159]
When watching a replay on Linux, this error comes up with the text:
"An error has occurred
stderr maxBuffer length exceeded"

Once this happens, the Dolphin instance exits.

This is using the AppImage distribution of slippi-desktop-app on Linux. This does still happen with the current version, and if required, I can try building with debugging enabled if possible to help debugging.

Some notes about this error:
- I can skip around the replay without problem.
- I can pause and the replay will not crash.
- It seems that this error is caused after a certain amount of time of the replay being played (After a few tests this seems to be around 1 min and 2 sec)

**Comment by NikhilNarayana** [comment]
This is likely happening due to GTK errors being emitted over stdout. This is fixed in the rewrite, but we won't be fixing it for the current desktop app. If you want support for mitigating this issue, please head over to the support channels on our discord @ https://slippi.gg/discord
