### ISSUE TITLE
Dolphin cannot load `.slp` files which locate the path including "full-width" character

### ISSUE THREAD

**Issue by Kounotori-ssbm** [project-slippi/slippi-desktop-app#26]
My friends say "Dolphin in Slippi desktop app cannot load slp files, it always say 'waiting for game..'" to me.

We're Japanese, so their username of Windows is "full-width" Japanese character (for example "安井").
They tried downloading slp file to the path including only "half-width" character, then the slp file could be loaded.

**Comment by JLaferri** [comment]
I believe I have succeeded in fixing this bug. Should be included in the next release. Thanks for making the issue :).

Here is the relevant commit:
https://github.com/project-slippi/Ishiiruka/commit/b0102b54436656b099cf4f92d3503368ee1d4e46

**Comment by Kounotori-ssbm** [comment]
Yayyy thank you so much!!
When are you going to release this fix?

**Comment by JLaferri** [comment]
@Kounotori-ssbm not quite sure yet, but I'll let you know when it's out! It will go out with the next release.
