### ISSUE TITLE
Kills that don't involve connected moves break the kills table

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/slippi-desktop-app#38]
In the file below, the falco dies off of a grab release on his third stock. The punish stat for this interaction lacks any moves so the kills table fails to generate and breaks the entire stats page.

[Game_20191008T211638.zip](https://github.com/project-slippi/slippi-desktop-app/files/3704346/Game_20191008T211638.zip)

**Comment by seant4** [comment]
Has this been fixed as of now? I looked in the code and it should assume an sd, if this is for something else i can look into it
