### ISSUE TITLE
Performance: Replay Browser's loading time is proportinal to number of replays

### ISSUE THREAD

**Issue by boulajp** [project-slippi/slippi-desktop-app#53]
Currently, there's no support for the pagination/segmentation of replays. The result of this is that every replay file must be loaded before the UI becomes usable.

After using slippi for a few months (accumulating about 2500 replays), my load time is about 15-20 seconds. Adding proper pagination support would allow for a constant load time of the desktop app.

**Comment by JLaferri** [comment]
Known issue. Part of the problem is that we can't sort by timestamps without loading all the files first. Probably the correct solution would be to do some kind of caching on the files.

A workaround for now is to just move your replays into sub-folders to have less replays per folder.

**Comment by boulajp** [comment]
Is that really the case? You could likely find all the files contained Slippi directory without too much overhead - since you're already including date/time information in the title, you could sort the file names without having to load the files.

**Comment by boulajp** [comment]
Alternatively, is it worth exploring alternative directory structures for dolphin to output the slippi files into? I was thinking you could generate a sub-directory by (year, month) pair. 

That way, you could easily paginate by month, which should give constant load times (assuming you played a constant number of games day-to-day)

**Comment by JLaferri** [comment]
The files aren't necessarily going to be named that way and the system supports the files being renamed. The timestamp is actually stored in the metadata of the file itself (which has to be parsed)

And yes a potential workaround is to manage the folder directory more strongly. But keep in mind that netplay is not the only use case we are solving for. Some people might download replays from slippi.gg. Some people will transfer replay files from their console (or consoles).

**Comment by JLaferri** [comment]
I think the best solution is some kind of a cache that stores file metadata information such that it doesn't have to parse them from each individual file every time (it would only need to do it for the new files)

**Comment by boulajp** [comment]
While a cache would still be beneficial in terms of startup performance, while starting work on that I realized that the larger performance hit arises from rendering each individual row and not initially loading and parsing the files as I suspected.

Since the rendering is the bottleneck, it would be more beneficial to optimize that step through a solution such as pagination right now. @JLaferri

**Comment by JLaferri** [comment]
When I tested this, loading the files from disc (esp the first time, presumably before the disc does some caching of the files) was the largest bottleneck.

That said, fixing the rendering would likely help too. I think virtualization might be a better option than pagination though. I think there might already be a PR for pagination but I don't think I liked the feel of it much.

**Comment by boulajp** [comment]
Interesting - I observed that if I reduce the number of files rendered to something very small in `renderFileSelection` within `FileLoader.js` (I just picked the first five files), my initial load time goes from ~20s to ~3s, and subsequent loads (opening the replay browser after going back to the main menu) has no delay. Because of this behavior, I concluded that its the render rather than the load with the largest overhead

**Comment by boulajp** [comment]
That being said I'd be interested in giving virtualization a go

**Comment by JLaferri** [comment]
Feel free, virtualization if done right should be a no-brainer to merge given that it wouldn't change the UI at all

**Comment by boulajp** [comment]
Unfortunately, Semantic UI doesn't appear to have virtualization support, so there would need to be UI level changes - namely using a UI framework that supports this such as `react-virtualized` for the table elements.

**Comment by JLaferri** [comment]
https://stackoverflow.com/questions/48077765/using-semantic-ui-react-with-react-virtualized

Not sure if this helps. But frankly I'm not in love with semantic UI lol but it might be too much trouble to not use it. Though if you want to try to make the table look like it does not without it, that would work. Could maybe still use the classes directly, not sure.

**Comment by a-sink-a-wait** [comment]
Is someone actively looking into this? I'd love to, if not!!!

**Comment by boulajp** [comment]
@a-sink-a-wait Yup, there's a PR open for this issue.

#58
