### ISSUE TITLE
Performance: Cache loaded file results

### ISSUE THREAD

**Issue by boulajp** [project-slippi/slippi-desktop-app#54]
Long [load times ](https://github.com/project-slippi/slippi-desktop-app/issues/53) are unfortunately not isolated to the startup of the desktop app - Upon returning back to the replay browser from a game stat screen, replays are reloaded from disk.

Consider adding application-level caching to previously loaded games.

**Comment by JLaferri** [comment]
I don't think this requires a separate issue. It's the same problem as the other issue.
