### ISSUE TITLE
Bug: Scroll position is no longer restored after returning to replay browser from a game

### ISSUE THREAD

**Issue by boulajp** [project-slippi/slippi-desktop-app#65]
After #62, the scroll position on the page is no longer restored after returning back to the replay browser from a game replay. This is because scroll position is restored in ‘componentDidMount’, which occurs before the game rows are rendered.

**Comment by JLaferri** [comment]
Fixed by https://github.com/project-slippi/slippi-desktop-app/commit/15e36a6bdb64a3f4218b13dc3c792adb0cb48154

**Comment by boulajp** [comment]
Thanks! I didn’t realize there was a ‘componentDidUpdate’ lifecycle method.
