### ISSUE TITLE
Regression: File list no longer updates when going to menu and returning to file browser

### ISSUE THREAD

**Issue by JLaferri** [project-slippi/slippi-desktop-app#67]
This action should trigger a full refresh.

You can repro by accessing the browser, adding a new file to the folder, pressing back, and returning to the browser. The new file will not be there

**Comment by Kethku** [comment]
I can't repro this. I think it has been fixed.

**Comment by NikhilNarayana** [comment]
Fixed by 9c55da7fe775082591e8c2d9345e5d8e74bed4ce
