### ISSUE TITLE
Add support for hiding or deleting "Unknown" time replays

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/slippi-desktop-app#71]
Lots of users are getting confused when they open up their replay browser and just see a bunch of `Unknown` time replays that aren't recent. While we have fixed the issue on the asm side, the browser will still be heavily populated with these replays for many users.

I'm leaving the issue kinda vague cause I want to see what people can come up with. Hiding or just straight up deletion is fine, but they should be optional. Maybe do both?

**Comment by nicfb** [comment]
Is this still needed after the addition from #77 ?

**Comment by NikhilNarayana** [comment]
yeah it really isn't needed anymore
