### ISSUE TITLE
Question: Unable to use semantic-react-ui's Dropdown component in this project

### ISSUE THREAD

**Issue by davidtranhq** [project-slippi/slippi-desktop-app#79]
I'm trying to use [semantic-react-ui's Dropdown menu component](https://react.semantic-ui.com/modules/dropdown/) to create a file filter in this project. The initial component renders fine, but the menu is invisible when clicked.

The relevant HTML is added to the document but the element is invisible: could this be conflicting with a style configuration I don't know about? (The button is clicked in this example)

![image](https://user-images.githubusercontent.com/30242944/87256902-85df5080-c464-11ea-81e5-29c5909eaaab.png)

And here is a working example with the exact same code outside the project:

https://codesandbox.io/s/semantic-ui-example-w6jro?file=/example.js

**Comment by NikhilNarayana** [comment]
closing due to lack of relevancy with the rewrite where we are switching to material-ui
