### ISSUE TITLE
Changing Install Location

### ISSUE THREAD

**Issue by Turbo1928** [project-slippi/slippi-desktop-app#8]
This isn't exactly a bug, but it would be really helpful if you chould choose the install location of Project Slippi rather than just having it default to the C drive. My C drive is essentially full, so I'd rather not put more programs on to it.

**Comment by JLaferri** [comment]
Unfortunately doing this would cause problems with file associations, URI associations, and perhaps auto-update too. Because of this I don't think I'm going to support it, sorry.
