### ISSUE TITLE
Slippi desktop app looks for `latest-linux.yml` in wrong release.

### ISSUE THREAD

**Issue by nicolaiskogheim** [project-slippi/slippi-desktop-app#87]
I just downloaded the latest Slippi Desktop app for Linux from slippi.gg, version 1.4.5.
When firing up the app, it looks like it just gets the latest release off of Github and expects to see a `latest-linux.yml`.
The latest release on Github is 1.5.1, but that was not built/released for linux, and there is no `latest-linux.yml`.

This is my first time trying the app so I don't know if what I then observed is relevant:
- Configuring paths went fine
- Could launch FM dolphin by clicking "Configure Dolphin". It says "Waiting for game"
- After configuring paths, I clicked the "Back button", but the app still says "Root Folder Missing".

App logs:
```
$ ./Slippi-Launcher-1.4.5-x86_64.AppImage                                                                                                                                                                       
[19:10:34.122] [info] App starting...
[19:10:34.326] [info] Handling URL...
[19:10:34.326] [info] 
[19:10:34.327] [info] protocol: null:, hostname: null
[19:10:35.544] [info] Checking for update
[19:10:36.808] [error] Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/project-slippi/slippi-desktop-app/releases/download/v1.5.1/latest-linux.yml): HttpError: 404 Not Found
"method: undefined url: https://github.com/project-slippi/slippi-desktop-app/releases/download/v1.5.1/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
```

After those startup logs, a dump of the request headers and a stack trace follows.

**Comment by NikhilNarayana** [comment]
Yeah we know this happens cause we haven't released a new linux version, but this shouldn't cause an issue anyways. If you are experiencing a crash then feel free to reopen.

**Comment by nicolaiskogheim** [comment]
It means the latest release on slippi.gg isn't working at all, though. It's just a bit confusing that there aren't any mention of it (except Discord, but y'know, not everyone is there).
The problem is that when you release a new linux version, you'll break it for everyone when releasing a windows exclusive version after it, and it will be broken until Linux gets the release. If the `latest-linux.yml` file is cached, then it's another story of course.

**Comment by NikhilNarayana** [comment]
The app should still work, it just won't be able to update. We've had multiple people use the Linux 1.4.5 AppImage without issue since we've pushed Windows only updates.
